version: "3.9"

services:
  inspectra-auth:
    build:
      context: ./inspectra-auth
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGO_URI=mongodb://mongo:27017/inspectra
    depends_on:
      - mongo
    volumes:
      - ./inspectra-auth:/app
    restart: always
    command: ./wait-for-it.sh mongo:27017 -- npm start

  mongo:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always

volumes:
  mongo_data:
