# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: InSpectra-Auth/package-lock.json
    - run:  |
        cd InSpectra-Auth  
        npm ci
    - run:  |
        cd InSpectra-Auth
        npm run build --if-present
    - name: Run Tests
      run:  |
        cd InSpectra-Auth
        npm test -- --testPathIgnorePatterns=auth.test.js
      env:
        GOOGLE_CLIENT_ID: 'test-client-id'
        GOOGLE_CLIENT_SECRET: 'test-client-secret'
        GOOGLE_CALLBACK_URL: 'http://localhost:3000/auth/callback'
